# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none

# Setup
title:               'Small Axe: Archipelagos'
tagline:             ''
description:         'A Small Axe Journal of Caribbean New Media and Digital Humanities.'
url:                 http://smallaxe.net/
baseurl:             "/Jekyll"

# Pandoc
gems:
  - jekyll-pandoc
markdown: pandoc
pandoc:
  extensions:
    - normalize
    - smart
    - csl: _styles/chicago.csl
    - bibliography: bibliography/references.bib

# About/contact
author:
  name:              Alex Gil
  url:               https://twitter.com/elotroalex
  email:             colibri.alex@gmail.com

# Custom vars
version:             0.0.1
